name: Cron job

on: 
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: printout
        run: echo 'Hello, world2!'
      - name: Set cron schedule
        uses: gr2m/set-cron-schedule-action@v2.0.2



