name: scrapes yahoo

on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: install python packages
        run: pip install yfinance
          
      - name: execute py script # run main.py
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "deglava@yahoo.com"
          git config --local user.name "deglava"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          git push
          
